# -*- coding: utf-8 -*-
"""Banking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AAAd633XMK3RImkgHlROwPCWE6dS-9JZ

Bank-Credit-Risk-and-Segmentation
"""

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score

import warnings
warnings.filterwarnings('ignore')

"""UPLOAD DATASET"""

import zipfile
import pandas as pd

with zipfile.ZipFile('/content/archive(3).zip', 'r') as zip_ref:
    zip_ref.extractall()

df = pd.read_excel('/content/Bank Loan Analysis Project.xlsx')
display(df.head())

from google.colab import drive
drive.mount('/content/Mydrive.')

"""DATA ANALANALYSIS"""

df.info()

print("Mavjud bo'lmagan qiymatlar:\n", df.isnull().sum())

df['desc'] = df['desc'].fillna('No description')
df['title'] = df['title'].fillna('Unknown')
print("Mavjud bo'lmagan qiymatlar:\n", df.isnull().sum())

print(f"DupDuplicate: {df.duplicated().sum()}")

print("\nUnique values ​​in categorical columns:")
for column in df.select_dtypes(include='object').columns:
    print(f"\nUstun: {column}")
    print(df[column].value_counts())

"""WE WILL REMOVE (CLEAN UP) THE DATA AND COLUMNS THAT AFFECT THE PERFORMANCE OF OUR MODEL"""

df.drop(['zip_code', 'desc', 'pymnt_plan', 'id', 'title'], axis=1, inplace=True)

df['emp_title'] = df['emp_title'].str.replace('n/a', '0')
df['emp_title'] = df['emp_title'].str.extract(r'(\d+)')
df['emp_title'] = df['emp_title'].fillna(0).astype(int)

df['emp_length'] = df['emp_length'].str.replace('n/a', '0')
df['emp_length'] = df['emp_length'].str.extract(r'(\d+)')
df['emp_length'] = df['emp_length'].fillna(0).astype(int)

df = pd.get_dummies(df, columns=['home_ownership', 'purpose', 'verification_status'], drop_first=True)

df = df[df['loan_status'].isin(['Fully Paid', 'Charged Off'])]
df['loan_status'] = df['loan_status'].apply(lambda x: 1 if x == 'Fully Paid' else 0)

df['term'] = df['term'].str.extract(r'(\d+)').astype(int)

grade_map = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7}
df['grade'] = df['grade'].map(grade_map)

df = pd.get_dummies(df, columns=['sub_grade'], drop_first=True)

df = pd.get_dummies(df, columns=['addr_state'], drop_first=True)

df['issue_d'] = pd.to_datetime(df['issue_d'])

df['issue_year'] = df['issue_d'].dt.year

df['issue_month'] = df['issue_d'].dt.month

df.drop('issue_d', axis=1, inplace=True)

df.info()

"""MODEL BUILDING

"""

from sklearn.model_selection import train_test_split

X = df.drop('loan_status', axis=1)
y = df['loan_status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42)

model.fit(X_train, y_train)

"""MODEL TRAINING XGBOOST"""

from xgboost import XGBClassifier
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

model = XGBClassifier(n_estimators=200, learning_rate=0.05, scale_pos_weight=5, random_state=42)

model.fit(X_train_res, y_train_res)

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

"""Visualize classes"""

import matplotlib.pyplot as plt
import pandas as pd

importances = model.feature_importances_
feature_names = X.columns
feature_imp = pd.Series(importances, index=feature_names).sort_values(ascending=False)

plt.figure(figsize=(10, 6))
feature_imp.head(10).plot(kind='barh', color='skyblue')
plt.title("10 factors that most affect credit risk")
plt.xlabel("Importance")
plt.gca().invert_yaxis()
plt.show()

!pip install imbalanced-learn

"""Balanced ML"""

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train_res, y_train_res)

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))